name: Deploy to moon.scs.torontomu.ca

on:
  push:
    branches:
      - stage

env:
  TARGET_DIR: "/home/avm/courses/cps847/<your_scs_id>"
  SERVER_NAME: ${{ secrets.SERVER_NAME }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to target
      run: |
        scp -r . $USERNAME@$SERVER_NAME:$TARGET_DIR
