# Generated by Django 4.1.7 on 2023-03-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="facilitator",
            field=models.CharField(default="Facilitator 1", max_length=200),
        ),
    ]
