name: Deploy

on:
  push:
    branches: [stage]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to target
      uses: appleboy/scp-action@master
      with: |
        host: ${{ secrets.DEPLOY_HOST }}
        port: ${{ secrets.DEPLOY_PORT }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        source: "./Lab2/index.html"
        target: ${{ secrets.DEPLOY_TARGET }}
